export type PageType =
  | 'dashboard'
  | 'customers'
  | 'customer-create'
  | 'customer'
  | 'products'
  | 'create-product'
  | 'import-products-from-file'
  | 'quotes'
  | 'create-quote'
  | 'quote-view'
  | 'send-quote-email'
  | 'settings'
  | 'customer-update'
